version: '3.7'

services:
  postgres:
    image: postgres:13.0-alpine
    env_file:
      - ./.env/.postgres/.env
    volumes:
      - postgres:/var/lib/postgresql/data

  django:
    build:
      context: .
      dockerfile: ./conf/backend/Dockerfile
    depends_on:
      - postgres
    env_file:
      - ./.env/.django/.env
      - ./.env/.postgres/.env    
    volumes:
      - ./dvd:/dvd      
      - django:/home/user
    ports:
      - "8001:8001"
    #init: true
    command: ['/run.sh']    

  quassar:
    build:
      context: .
      dockerfile: ./conf/frontend/Dockerfile
    env_file:
      - ./.env/.quassar/.env
    volumes:
      - ./dvd:/dvd
      #- ./conf/frontend/scripts:/scripts
      - quassar:/home/user
    init: true
    #command: ['/scripts/run.sh']

  nginx:
    image: nginx:1.19-alpine
    env_file:
      - ./.env/.nginx/.env
    depends_on:
      - django
      - quassar
    volumes:
      - ./conf/nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./conf/nginx/run.sh:/run.sh
    ports:
      - '8000:8000'
    #command: ['/run.sh']

volumes:
  postgres:
  django:
  quassar: