version: '3.7'

services:
  postgres:
    image: postgres:13.0-alpine
    env_file:
      - ./.env/.postgres/.env
    volumes:
      - postgres:/var/lib/postgresql/data

  django:
    build:
      context: .
      dockerfile: ./conf/backend/Dockerfile
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.env/.django/.env
      - ./.env/.postgres/.env    
    volumes:
      - ./dvd:/dvd      
      - django:/home/user
    ports:
      - "8001:8001"
    #init: true
    command: ['/run.sh']    

  quasar:
    build:
      context: .
      dockerfile: ./conf/frontend/Dockerfile
    env_file:
      - ./.env/.quasar/.env
    volumes:
      - ./dvd:/dvd
      - ./conf/frontend/scripts:/scripts
      - quasar:/home/user
    ports:
      - "8002:8002"
    init: true
    command: ['/scripts/run.sh']
    #command: npm run dev

  nginx:
    image: nginx:1.19-alpine
    env_file:
      - ./.env/.nginx/.env
    depends_on:
      - django
      - quasar
    volumes:
      - ./conf/nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./conf/nginx/run.sh:/run.sh
    ports:
      - "8009:8009"      
    command: ['/run.sh']
  
  redis:
    image: redis:5.0
    container_name: redis

volumes:
  postgres:
  django:
  quasar: