# Generated by Django 3.1.7 on 2021-05-17 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HiveCatalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, editable=False)),
                ('name', models.CharField(help_text='Nombre del catálogo', max_length=50, verbose_name='nombre')),
                ('description', models.TextField(help_text='Descripción del catálogo', verbose_name='descripcion')),
                ('catalogue', models.CharField(help_text='Id del catálogo', max_length=150, verbose_name='id')),
                ('twoValidation', models.BooleanField(default=False, help_text='Bandera de si existe catálogo o si esta activo o no', verbose_name='doble validacion')),
                ('isPublic', models.BooleanField(default=True, help_text='Bandera de si existe catálogo o si esta activo o no', verbose_name='¿es publico?')),
                ('isActive', models.BooleanField(help_text='Bandera de si existe catálogo o si esta activo o no')),
                ('views', models.IntegerField(help_text='Número de veces que se ha consultado', verbose_name='vistas')),
                ('modifications', models.IntegerField(help_text='Número de veces que se ha modificado algún registro', verbose_name='modificaciones')),
                ('downloads', models.IntegerField(help_text='Número de veces que se ha descargado el catálogo', verbose_name='descargas')),
                ('creationDate', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación', verbose_name='fecha creacion')),
                ('modificationDate', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificación', verbose_name='fecha modificacion')),
                ('administrators', models.ManyToManyField(related_name='_hivecatalogue_administrators_+', to=settings.AUTH_USER_MODEL, verbose_name='Lider de Gobierno de datos')),
                ('groups', models.ManyToManyField(blank=True, related_name='_hivecatalogue_groups_+', to='auth.Group')),
                ('lastModifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ultimo en modificar')),
                ('superGroups', models.ManyToManyField(blank=True, related_name='_hivecatalogue_superGroups_+', to='auth.Group')),
                ('superUsers', models.ManyToManyField(blank=True, related_name='_hivecatalogue_superUsers_+', to=settings.AUTH_USER_MODEL, verbose_name='Editores')),
                ('users', models.ManyToManyField(blank=True, related_name='_hivecatalogue_users_+', to=settings.AUTH_USER_MODEL, verbose_name='Visualizadores')),
            ],
            options={
                'verbose_name': 'Catálogo Hive',
                'verbose_name_plural': 'Catálogos Hive',
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
